# Generated by Django 2.2.2 on 2019-07-06 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('description', models.CharField(max_length=255, verbose_name='Оисание курса')),
            ],
            options={
                'verbose_name': 'Курс обучения',
                'verbose_name_plural': 'Курсы обучения',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PlanDayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('body', models.CharField(max_length=1000, verbose_name='План')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес проведения')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_plans', to=settings.AUTH_USER_MODEL, verbose_name='Лектор')),
            ],
            options={
                'verbose_name': 'План дня',
                'verbose_name_plural': 'Планы дней',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя отправителя')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('theme', models.CharField(max_length=100, verbose_name='Тема')),
                ('body', models.CharField(max_length=1000, verbose_name='Сообщение')),
                ('status', models.IntegerField(choices=[(0, 'На рассмотрении'), (1, 'Одобрено'), (2, 'Отклонено')], default=0)),
                ('answer', models.CharField(max_length=1000, verbose_name='Ответ')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Вопрос от пользователя',
                'verbose_name_plural': 'Вопросы от пользоватлей',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='TypeCourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип курса',
                'verbose_name_plural': 'Типы курсов',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('date_schedule', models.DateTimeField(verbose_name='Дата проведения')),
                ('number_day', models.PositiveSmallIntegerField(verbose_name='Порядновый номер дня проведения')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='mickroservices.CourseModel', verbose_name='курс')),
                ('plansday', models.ManyToManyField(related_name='schedules', to='mickroservices.PlanDayModel', verbose_name='планы дня')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ['date_schedule', 'number_day'],
            },
        ),
        migrations.AddField(
            model_name='plandaymodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='mickroservices.TypeCourseModel', verbose_name='типы курсов'),
        ),
    ]
