# Generated by Django 2.2.2 on 2019-07-15 19:35

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('mickroservices', '0002_newspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextTemplate',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Текстовый шаблон',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='newspage',
            options={'verbose_name': 'Новости'},
        ),
        migrations.AddField(
            model_name='newspage',
            name='preview',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
