# Generated by Django 2.2.2 on 2019-07-17 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('mickroservices', '0003_auto_20190715_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание курса'),
        ),
    ]
