# Generated by Django 2.2.2 on 2019-07-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mickroservices', '0005_marketingmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingmaterial',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Акции'), (1, 'Перед открытием'), (2, 'Меню'), (3, 'Другие макеты'), (4, 'Видеоролики'), (5, 'Аудиоролики')], default=0, verbose_name='Тип'),
        ),
    ]
