# Generated by Django 2.2.2 on 2019-07-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mickroservices', '0006_marketingmaterial_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulemodel',
            options={'ordering': ['date_schedule'], 'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.RemoveField(
            model_name='schedulemodel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='schedulemodel',
            name='number_day',
        ),
        migrations.RemoveField(
            model_name='schedulemodel',
            name='plansday',
        ),
        migrations.RemoveField(
            model_name='schedulemodel',
            name='title',
        ),
        migrations.AddField(
            model_name='schedulemodel',
            name='url_lesson',
            field=models.CharField(default=0, max_length=255, verbose_name='Ссылка на расписание'),
            preserve_default=False,
        ),
    ]
