# Generated by Django 2.2.2 on 2019-07-18 16:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mickroservices', '0007_auto_20190718_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=12, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='schedulemodel',
            name='url_lesson',
            field=models.URLField(max_length=255, verbose_name='Ссылка на расписание'),
        ),
    ]
