# Generated by Django 2.2.3 on 2019-07-29 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('mickroservices', '0010_ideamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSushi',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtaildocs.Document')),
                ('doc_type', models.IntegerField(choices=[(0, 'Техкарты'), (1, 'Регламенты')], default=0)),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'abstract': False,
            },
            bases=('wagtaildocs.document',),
        ),
    ]
