# Generated by Django 2.2.3 on 2019-08-29 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mickroservices', '0015_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsushi',
            name='sub_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mickroservices.Subjects', verbose_name='тематика'),
            preserve_default=False,
        ),
    ]
