# Generated by Django 2.2.3 on 2019-08-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mickroservices', '0016_documentsushi_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Техкарты'), (1, 'Регламенты'), (2, 'Акции'), (3, 'Перед открытием'), (4, 'Меню'), (5, 'Другие макеты'), (6, 'Видеоролики'), (7, 'Аудиоролики'), (8, 'Личные документы'), (9, 'Личные счета')], default=0),
        ),
    ]
