# Generated by Django 2.2.3 on 2019-09-05 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mickroservices', '0019_auto_20190905_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_faq', to=settings.AUTH_USER_MODEL),
        ),
    ]
