# Generated by Django 2.2.3 on 2019-09-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mickroservices', '0020_questionmodel_user'),
        ('mickroservices', '0019_auto_20190903_0852'),
    ]

    operations = [
    ]
