# Generated by Django 2.2.3 on 2019-10-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mickroservices', '0022_ideamodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
