# Generated by Django 2.2.3 on 2019-10-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mickroservices', '0023_questionmodel_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='announcement',
            field=models.TextField(blank=True),
        ),
    ]
