# Generated by Django 2.2.3 on 2020-03-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mickroservices', '0024_newspage_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspage',
            options={'verbose_name': 'Программы'},
        ),
    ]
