# Generated by Django 2.2.3 on 2020-03-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mickroservices', '0026_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='coast',
            field=models.IntegerField(blank=True, default=2500),
            preserve_default=False,
        ),
    ]
