# Generated by Django 2.2.3 on 2020-03-07 22:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mickroservices', '0027_newspage_coast'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='places_limited',
            field=models.BooleanField(default=False, verbose_name='Ограничено мест'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='subscription',
            field=models.BooleanField(default=False, verbose_name='Абонимент'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Основная информация о программе'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='coast',
            field=models.IntegerField(blank=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Фоновая картинка'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='preview',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Превью для карточки'),
        ),
    ]
