# Generated by Django 2.2.3 on 2020-03-07 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mickroservices', '0028_auto_20200308_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspage',
            old_name='coast',
            new_name='cost',
        ),
    ]
