# Generated by Django 2.2.3 on 2020-05-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mickroservices', '0030_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='type_classes',
            field=models.SmallIntegerField(choices=[(0, 'Индивидуальная тренировка'), (1, 'Индивидуальная тренировка 1+1')], default=0, verbose_name='Тип занятия'),
        ),
    ]
