# Generated by Django 2.2.12 on 2020-05-17 13:51

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mickroservices', '0031_newspage_type_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='texttemplate',
            name='extra_body',
            field=wagtail.core.fields.StreamField([('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True),
        ),
    ]
