# Generated by Django 2.2.3 on 2019-08-31 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sushi_app', '0028_auto_20190826_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='body message')),
                ('status', models.SmallIntegerField(choices=[(0, 'в ожидании'), (1, 'прочтена')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_messages', to='sushi_app.UserProfile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_messages', to='sushi_app.UserProfile')),
            ],
        ),
    ]
