# Generated by Django 2.2.3 on 2019-09-02 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mickroservices', '0018_auto_20190830_1214'),
        ('chat', '0003_auto_20190901_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mickroservices.IdeaModel'),
        ),
        migrations.AddField(
            model_name='message',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mickroservices.QuestionModel'),
        ),
    ]
