# Generated by Django 2.2.3 on 2019-07-28 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0014_auto_20190728_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'is_manager': True}, on_delete=django.db.models.deletion.CASCADE, related_name='feed_manager', to='sushi_app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_responsible', to='sushi_app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'is_manager': True}, on_delete=django.db.models.deletion.CASCADE, related_name='requests_manager', to='sushi_app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_responsible', to='sushi_app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'is_manager': True}, on_delete=django.db.models.deletion.CASCADE, related_name='task_manager', to='sushi_app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_responsible', to='sushi_app.UserProfile'),
        ),
    ]
