# Generated by Django 2.2.3 on 2019-07-28 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailusers', '0009_userprofile_verbose_name_plural'),
        ('sushi_app', '0017_auto_20190728_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wagtail_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='wagtailusers.UserProfile'),
            preserve_default=False,
        ),
    ]
