# Generated by Django 2.2.3 on 2019-07-28 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0018_userprofile_wagtail_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wagtail_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='wagtailusers.UserProfile'),
        ),
    ]
