# Generated by Django 2.2.3 on 2019-08-03 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0019_auto_20190729_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date_pub',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='source',
            field=models.CharField(default='base', max_length=256),
            preserve_default=False,
        ),
    ]
