# Generated by Django 2.2.3 on 2019-08-04 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0021_auto_20190804_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(default='Москва', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='entity_name',
            field=models.CharField(default='Door', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='responsibles',
            field=models.ManyToManyField(limit_choices_to={'is_partner': True}, related_name='shop_responsible', to='sushi_app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'is_partner': True}, on_delete=django.db.models.deletion.DO_NOTHING, to='sushi_app.UserProfile'),
        ),
    ]
