# Generated by Django 2.2.3 on 2019-08-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0023_auto_20190804_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messeges',
            name='product',
        ),
        migrations.AddField(
            model_name='messeges',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sushi_app.Feedback'),
        ),
        migrations.AddField(
            model_name='messeges',
            name='requests',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sushi_app.Requests'),
        ),
        migrations.AddField(
            model_name='messeges',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sushi_app.Task'),
        ),
    ]
