# Generated by Django 2.2.3 on 2019-08-04 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sushi_app', '0024_auto_20190804_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messeges',
            old_name='user',
            new_name='from_user',
        ),
        migrations.RemoveField(
            model_name='messeges',
            name='accepter',
        ),
        migrations.AddField(
            model_name='messeges',
            name='to_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
