# Generated by Django 2.2.3 on 2019-08-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0025_auto_20190804_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='checks',
            field=models.ManyToManyField(blank=True, related_name='_shop_checks_+', to='mickroservices.DocumentSushi'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='docs',
            field=models.ManyToManyField(blank=True, related_name='_shop_docs_+', to='mickroservices.DocumentSushi'),
        ),
    ]
