# Generated by Django 2.2.3 on 2019-08-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0027_auto_20190825_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
