# Generated by Django 2.2.3 on 2019-09-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0028_auto_20190826_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Решен'), (1, 'Обрабатывается'), (2, 'Не решен')], default=2),
        ),
    ]
