# Generated by Django 2.2.3 on 2019-09-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0029_auto_20190902_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Отработан'), (1, 'Не отработан')], default=1),
        ),
    ]
