# Generated by Django 2.2.3 on 2019-09-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0030_auto_20190902_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='messeges',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
