# Generated by Django 2.2.3 on 2019-09-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0031_messeges_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messeges',
            name='file',
            field=models.FileField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='scan',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
