# Generated by Django 2.2.3 on 2019-10-13 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0033_auto_20190916_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'is_partner': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shop_partner', to='sushi_app.UserProfile'),
        ),
    ]
