# Generated by Django 2.2.3 on 2019-10-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0034_auto_20191013_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messeges',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
