# Generated by Django 2.2.3 on 2019-10-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0035_auto_20191022_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
