# Generated by Django 2.2.3 on 2020-03-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0037_auto_20200322_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
    ]
