# Generated by Django 2.2.3 on 2020-03-22 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sushi_app', '0038_auto_20200322_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL, verbose_name='Посетитель занятия'),
        ),
    ]
