# Generated by Django 2.2.3 on 2020-03-22 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0039_classes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
