# Generated by Django 2.2.3 on 2020-04-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0040_classes_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='is_not_attended',
            field=models.BooleanField(default=False, verbose_name='Пропущено'),
        ),
    ]
