# Generated by Django 2.2.3 on 2020-05-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0044_classes_date_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='pay_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
